GET http://localhost:3003/api/blogs

#### POST blogs
POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2YTVhMzMyMzRjNTJkMjMyMjVjZWY3MTciLCJpYXQiOjE3ODQyOTYzODB9.isvlE3WL8mV7774DNYhtggIYizQjMQaFt_bW_0phqIc
Content-Type: application/json

{
    "title": "titled",
    "author": "admin",
    "url": "url",
    "likes": "0"
}

#### POST blogs error
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "titled",
    "author": "admin",
    "url": "url",
    "likes": "0"
}

#### DELETE blog
DELETE http://localhost:3003/api/blogs/6a5a37f00304cf78647aef54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2YTVhMzMyMzRjNTJkMjMyMjVjZWY3MTciLCJpYXQiOjE3ODQyOTYzODB9.isvlE3WL8mV7774DNYhtggIYizQjMQaFt_bW_0phqIc


########################### USERS
GET http://localhost:3003/api/users
#### POST user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "user2",
    "name": "user",
    "password": "123"
}

########################### LOGIN
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "user2",
    "password": "123"
}